### ISSUE TITLE
Adding service in layer control through dnd widget

### ISSUE THREAD

**Issue by deepal13** [BrianBunker/cmv-widgets#33]
Hello Brian,

I am using your dnd widget to add shape file and services. Is it possible to show the added service in the layer control menu? The purpose is to turn on/off the layers in the service.

Thanks

**Comment by tmcgee** [comment]
@deepal13 Support for adding layers/services to the layerControl widget using topic publish/subscribe was added to cmv in the current develop branch in the cmv repo. If you are using that version of cmv with the layerControl widget and the dnd widget, the layer/service will be added automatically.

**Comment by deepal13** [comment]
@tmcgee I just downloaded the code from https://github.com/BrianBunker/cmv-widgets and tried it. It didn't add it to layer control. Am I referring the wrong link?

**Comment by tmcgee** [comment]
That DnD widget is the correct version. However, at present this will only work with the layerControl widget found in the un-released [develop branch](https://github.com/cmv/cmv-app/tree/develop) of cmv.

**Comment by deepal13** [comment]
@tmcgee I downloaded the code from the link you provided. The widget adds the service but in layerControl widget it doesn't expand to show all its layers.

![dndscreenshot](https://cloud.githubusercontent.com/assets/7016949/16673741/c27266e6-4465-11e6-9113-dce231f44850.png)

**Comment by tmcgee** [comment]
@deepal13 I have a few changes to both the layerControl and Dnd widgets to handle more Service types and better error handling. I will be submitting PRs for both in this repo and in the cmv repo.

**Comment by tmcgee** [comment]
@deepal13 PR #34 which has already been committed addresses the changes needed to the Dnd widget.

**Comment by tmcgee** [comment]
@deepal13 Here's the pending [PR](https://github.com/cmv/cmv-app/pull/568) in the cmv repo that addresses the changes needed to the layerControl widget.

**Comment by deepal13** [comment]
@tmcgee I tried the updated code, it still adds in drag-n-drop widget. Can you please check once?
Thanks

**Comment by tmcgee** [comment]
@deepal13 Do you have an example service that demonstrates the issue?

**Comment by deepal13** [comment]
@tmcgee I added the following service: http://nowcoast.noaa.gov/arcgis/rest/services/nowcoast/guidance_model_ocean_grtofs_offsets/MapServer
![image](https://cloud.githubusercontent.com/assets/7016949/17451925/7252b8de-5b1f-11e6-8e28-a0fda0b39765.png)

**Comment by tmcgee** [comment]
@deepal13 I don't see any issues with adding that service with DnD:

![image](https://cloud.githubusercontent.com/assets/200780/17452229/175700e0-5b22-11e6-8c65-21953dd322d9.png)

**Comment by deepal13** [comment]
I downloaded the code from: https://github.com/BrianBunker/cmv-widgets.

Can you please share the code link?

**Comment by tmcgee** [comment]
@deepal13 That is correct for the DnD widget. For the layerControl widget, you will need to use the code from the [`develop` branch](https://github.com/cmv/cmv-app/tree/develop) of cmv.  Here is a [working example](http://cmv-app-with-dnd-tmcgee13.c9users.io/viewer/) that will be running for a few days.

**Comment by deepal13** [comment]
@tmcgee  It is working now but as soon as I turn on/off any layer of the added service, the service vanishes from map and doesn't turn back on.

**Comment by deepal13** [comment]
@tmcgee

**Comment by tmcgee** [comment]
@deepal13 I see the behavior you describe. This is because the DnD widget [assigns the url](https://github.com/BrianBunker/cmv-widgets/blob/master/DnD/DnD.js#L380) of the service as the layer id. Instead of using the url, I think it would be better to assign a random id such as what happens for other types such as [shape files](https://github.com/BrianBunker/cmv-widgets/blob/master/DnD/DnD.js#L554-L558) or exclude the id and let the map assign one like `Layer123`.

**Comment by tmcgee** [comment]
@deepal13 Try again with the latest DnD widget. Yesterday I added code to create layer IDs instead using the url.

**Comment by deepal13** [comment]
@tmcgee It works fine now. Thank you so much.
I want to request you to please add a feature to change color/symbols of layer.
Thanks again.

**Comment by deepal13** [comment]
@tmcgee I am having trouble with printing. When I am using a secure service with proxy setup, the print fails giving error.
error Error: Unable to complete operation.
    at Error (native)
    at Object.g.load (https://js.arcgis.com/3.17compact/init.js:663:426)
    at https://js.arcgis.com/3.17compact/init.js:87:450
    at c (https://js.arcgis.com/3.17compact/init.js:103:393)
    at d (https://js.arcgis.com/3.17compact/init.js:103:182)
    at resolve.callback (https://js.arcgis.com/3.17compact/init.js:105:10)
    at c (https://js.arcgis.com/3.17compact/init.js:104:96)
    at d (https://js.arcgis.com/3.17compact/init.js:103:182)
    at resolve.callback (https://js.arcgis.com/3.17compact/init.js:105:10)
    at https://js.arcgis.com/3.17compact/init.js:92:118

**Comment by tmcgee** [comment]
@deepal13 This is not the right place for new requests or asking for support other than for @BrianBunker widgets. Please submit your issues at the cmv-app repo or post questions on gis.stackexchange.
